name: peer5
description: Flutter plugin to integrate with the Peer5 native SDKs on Android and iOS.
version: 1.0.0+1
homepage: https://peer5.com
repository: https://github.com/ianko/peer5_flutter
issue_tracker: https://github.com/ianko/peer5_flutter/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: dev.ianko.peer5
    pluginClass: Peer5Plugin
